source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails', '4.2.5'
gem 'pg', '~> 0.15'
gem 'rack-cors'
gem 'airbrake', '~> 4.3'
gem 'devise', '~> 3.5.3'
gem 'omniauth-facebook', '~> 4.0.0'
gem 'fb_graph2', '~> 0.9.0'
gem 'rest-client'
gem 'jbuilder'
gem 'date_validator'
gem 'validates_serialized', '~> 0.0.1'
gem 'activerecord-import'
gem 'active_model_serializers'
gem 'kaminari'
gem 'simple_enum', '~> 2.3.0'
gem 'delayed_job_active_record'
gem 'delayed-plugins-airbrake'
gem 'newrelic_rpm'

gem 'sass-rails', '~> 5.0'
gem 'compass-rails', '~> 2.0.4'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails', '~> 2.3.0'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'materialize-sass'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'reset-css', '~> 0.0.3'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'therubyracer'
  gem 'pry-rails'
  gem 'dotenv-rails'
  gem 'parallel_tests'
end

group :test do
  gem 'database_cleaner'
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'faker'
  gem 'factory_girl'
end
