json.id t_deposit.id
json.coins t_deposit.coins
json.currency t_deposit.currency.name
json.country t_deposit.country.name
json.payment_service t_deposit.payment_service.name
json.transaction_id t_deposit.transaction_id
json.price t_deposit.price
json.operator t_deposit.operator
json.type t_deposit.deposit_type
json.detail t_deposit.detail
json.date t_deposit.created_at
